version: "3.6"

services:
  cehatpay-listener-service:
    image: "idprm/cehatpay-listener-service:latest"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    ports:
      - 9100:9100
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/log/payment:/logs
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cehatpay-consumer-service:
    image: "idprm/cehatpay-consumer-service:latest"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/log/payment:/logs
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
